---
"Currently Online": CO1
"Currently AFK": CO2
"Currently Queued": CO3
"Currently Offline": CO4
"Currently Lagging": CO5
"Currently Loading": CO6
"Currently Salty": CO7
"Currently Insane": CO8
"Currently Confused": CO9
"Currently Capped": CO10
